### ISSUE TITLE
Regarding power supply to the carrier board.

### ISSUE THREAD

**Issue by Arna-Maity** [WeActTC/WeAct-TX1_2-CB#1]
Is the XT30 connector the only way to power up the carrier board or can we boot the board over the usb c interface also?

**Comment by Greetrix** [comment]
Hi, only XT30 connector in this carrier board.

**Comment by Arna-Maity** [comment]
So we can power the CB from anywhere between 9-19v right? So a 12v supply would be fine I suppose? Is there an estimate on how much power the CB might be drawing at full load so that I can decide on the kind of supply I need to use?

**Comment by Greetrix** [comment]
Hi, Yes, can 9-19V, 12V will better. Power decided the core board, we suggest use the 12V5A power or more.

**Comment by Arna-Maity** [comment]
Thanks a lot!

**Comment by Arna-Maity** [comment]
![image](https://github.com/WeActStudio/WeAct-TX1_2-CB/assets/32426434/0447ef9b-5344-4495-a50e-5b76f4cb3aa0)

In the XT30 power connector in the above image which are the positive and negative terminals?

**Comment by Greetrix** [comment]
circular pad is negative.
